### ISSUE TITLE
Issue Regarding Browser and Reddit History 

### ISSUE THREAD

**Issue by Kannav02** [ShwaasA/memebreak#3]
Hi , I tried out your extension , it was good , just had few issues , one of them being that can't we have any alternative to tracking the user history on Reddit and the Browser History as well, I know the memes are being sourced from Reddit , but why to track the person's reddit history in order to do so, The History part might concern a lot of users and prevent the extension from not being used.

**Comment by ShwaasA** [comment]
Thanks for the feedback, we will fix it as soon as possible.
Sorry for any inconveniences!
